version: '3.8'

configs:
  origin1_cfg:
    file: ./conf/origin1.conf
  origin2_cfg:
    file: ./conf/origin2.conf
  proxy_cfg:
    file: ./conf/proxy.conf

services:
  srs-origin-1:
    image: ossrs/srs:v7.0.157
    container_name: srs-origin-1
    hostname: srs-origin-1
    restart: always
    entrypoint: [""]
    ports:
      - "11935:1935"
      - "11986:1986"
      - "18080:8080"
      - "18000:8000/udp"
    volumes:
      - /home/lumingwei/srs/hls/origin1:/usr/local/srs/objs/nginx/html
      - /home/lumingwei/srs/recordings/origin1:/data/recordings
    configs:
      - source: origin1_cfg
        target: /tmp/srs.conf
    command: ./objs/srs -c /tmp/srs.conf

  srs-origin-2:
    image: ossrs/srs:v7.0.157
    container_name: srs-origin-2
    hostname: srs-origin-2
    restart: always
    entrypoint: [""]
    ports:
      - "12935:1935"
      - "12986:1986"
      - "19080:8080"
      - "19000:8000/udp"
    volumes:
      - /home/lumingwei/srs/hls/origin2:/usr/local/srs/objs/nginx/html
      - /home/lumingwei/srs/recordings/origin2:/data/recordings
    configs:
      - source: origin2_cfg
        target: /tmp/srs.conf
    command: ./objs/srs -c /tmp/srs.conf

  srs-proxy:
    image: ossrs/srs:v7.0.157
    container_name: srs-proxy-q
    hostname: srs-proxy
    restart: always
    entrypoint: [""]
    ports:
      - "1935:1935"
      - "1986:1986"
      - "8080:8080"
      - "8000:8000/udp"
    depends_on:
      - srs-origin-1
      - srs-origin-2
    configs:
      - source: proxy_cfg
        target: /tmp/srs.conf
    command: ./objs/srs -c /tmp/srs.conf

